# Generated by Django 5.1.4 on 2025-01-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_usedtechnology_color"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="site_logo",
            field=models.ForeignKey(
                help_text="Please, upload a sitelogo .",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="text_logo",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
